blog/urls.py
from django.contrib import admin
from django.urls import path
from .views import *
from blog.views import *
from django.conf import settings
from django.conf.urls.static import static



if settings.DEBUG: 

    urlpatterns = [
        path('admin/', admin.site.urls),
        path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
        path('',homepage, name = 'home'),
        path('register/', register, name='register'),
        path('login/', login_view, name='login'),
        path('crea_post/', CreaPost.as_view(), name='crea_post'),
        path('crea_post/<int:pk>', BlogPostModifica.as_view(), name='modifica_post'),
        path('elimina_post/<str:pk>', BlogPostDelete.as_view(), name='elimina_post'),
        path('view_post/<int:post_id>/', view_post, name='view_post'),
        path("postslist/", AdminPostsListView.as_view(), name="adminpostslist"),
        path("logout/", LogoutView.as_view(), name="customerlogout"),
        path('<pk>/update', BlogPostModifica.as_view()),
        path("logout/", logout, name="logout")    
        ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User
import os
from pathlib import Path
from django.views.generic.edit import UpdateView

BASE_DIR = Path(__file__).resolve().parent.parent

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="admins")
    mobile = models.CharField(max_length=20)

    def __str__(self):
        return self.user.username

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name

class BlogPost(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='', blank=True, null=True)
    view_count = models.PositiveIntegerField(default=0)
    traccia = models.FileField(upload_to='tracce/', validators=[FileExtensionValidator(['gpx'])] , blank=True, null=True )    
    def __str__(self):
        return self.title

class BlogImage(models.Model):
    blogpost = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='seconde/' )
    
    def __str__(self):
        return self.blogpost.title

blog/forms.py
from django import forms
from .models import * 
from django.contrib.auth.forms import UserCreationForm



class BlogPostForm(forms.ModelForm):
    more_images = forms.FileField(required=False, widget=forms.FileInput(attrs={
    "class": "form-control",
    "multiple": True
    }))

    class Meta:
        model = BlogPost
        fields = ['title', 'content','image', 'traccia']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control-file'})
        }




class CustomerRegistrationForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.CharField(widget=forms.EmailInput())

    class Meta:
        model = Customer
        fields = ["username", "password", "email", "full_name", "address"]

    def clean_username(self):
        uname = self.cleaned_data.get("username")
        if User.objects.filter(username=uname).exists():
            raise forms.ValidationError(
                "Customer with this username already exists.")

        return uname


class CustomerLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())


# Questo modulo è un ModelForm basato sul modello BlogPost creato in precedenza.
# La classe Meta viene utilizzata per specificare il modello su cui si basa il modulo
# e i campi che devono essere inclusi nel modulo.
# In questo esempio, i campi nel modulo sono 'titolo', 'contenuto' e 'immagine' che sono
# gli stessi campi nel modello BlogPost.

# Puoi anche utilizzare gli attributi dei widget nella classe Meta per specificare diversi 
# tipi di widget per ogni campo del modulo.  
# Questo aggiungerà la classe 'form-control' ai campi title e content, e 'form-control-file' 
# al campo immagine Una volta definito il modulo, puoi usarlo nella vista create_blog_post 
# che ho fornito in precedenza per gestire la creazione di nuovi post del blog.
# Per favore fatemi sapere se avete domande o se c'è qualcos'altro in cui posso aiutarvi.


class RegistrationForm(forms.Form):
    username = forms.CharField(max_length=30)
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirmation = forms.CharField(widget=forms.PasswordInput)

blog/views.py
from django.views.generic import View, TemplateView, CreateView, FormView, DeleteView, ListView
from django.contrib.auth import authenticate, login, logout 
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.http import JsonResponse
from django.conf import settings
from django.contrib.auth.forms import UserCreationForm
from django.db.models import Q
from django.contrib import messages
from .models import *
from .forms import *
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponse, HttpResponseRedirect

class AdminLoginView(FormView):
    template_name = "adminlogin.html"
    form_class = CustomerLoginForm
    success_url = "../postslist/"

    def form_valid(self, form):
        uname = form.cleaned_data.get("username")
        pword = form.cleaned_data["password"]
        usr = authenticate(username=uname, password=pword)
        if usr is not None and Admin.objects.filter(user=usr).exists():
            login(self.request, usr)
        else:
            return render(self.request, self.template_name, {"form": self.form_class, "error": "Invalid credentials"})
        return super().form_valid(form)

#  You can't use Decorators above class inherit LoginRequiredMixin in your class. Use adminrequired mixin
class AdminRequiredMixin(object):
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and Admin.objects.filter(user=request.user).exists():
            pass
        else:
            return redirect("/admin-login/")
        return super().dispatch(request, *args, **kwargs)



def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'register.html', {'form': form})


def homepage(request):
    return HttpResponse ("<h1>Homepage</h1>")


def chi_siamo(request):
    return HttpResponse ("<h2>Chi siamo</h2>")


def contatti(request):
    return HttpResponse ("<h3>Contattaci</h3>") 

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # Log in the user
            user = form.get_user()
            login(request, user)
            return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form})


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect("/")

def view_post(request, post_id):
    blogpost = BlogPost.objects.get(pk=post_id)
    blogpost.view_count += 1
    blogpost.save()
    return render(request, 'view_post.html', {'blogpost': blogpost})
    


class AdminPostsListView(AdminRequiredMixin, ListView):
    template_name = "adminpostslist.html"
    queryset = BlogPost.objects.all().order_by("-id")
    context_object_name = "allposts"


class CreaPost(AdminRequiredMixin,CreateView):
    template_name = "create_post.html"
    form_class = BlogPostForm

    def get_success_url(self):
        return reverse('view_post',args=(self.object.id,))

    def form_valid(self, form):
        p = form.save()
        images = self.request.FILES.getlist("more_images")
        for i in images:
            BlogImage.objects.create(blogpost=p, image=i)
        return super().form_valid(form)    
    

class BlogPostDelete(AdminRequiredMixin, DeleteView):
    # specify the model you want to use
    model = BlogPost
    success_url ="../postslist"
    template_name = "elimina_post.html"
    success_message = "Post eliminato con successo."
    
    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        self.object = self.get_object()
        testo = 'Post ' + str(self.object.title) + ' eliminato.'
        return super(BlogPostDelete, self).delete(request, *args, **kwargs)


class BlogPostModifica(AdminRequiredMixin,UpdateView):
    model = BlogPost
    form_class = BlogPostForm
    template_name = "create_post.html"
    success_url ="/"

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        self.object = self.get_object()
        context['titolo'] = 'Modifica del Post' + ' nr. ' + str(self.object)
        return context

    def form_invalid(self, form):
        messages.error(self.request, "Errore durante la compilazione")
        return super().form_invalid(form)
    
    def form_valid(self, form):
        messages.success(self.request, "Modifica effettuata con successo")
        original_instance = BlogPost.objects.get(pk=self.object.id)
        p = form.save()
        images = self.request.FILES.getlist("more_images")
        if len(images) > 0:
            BlogImage.objects.filter(blogpost=original_instance.id).delete( )
            #YourModel.objects.filter().delete()
            for i in images:
                BlogImage.objects.create(blogpost=p, image=i)
        super().form_valid(form)    
        return HttpResponseRedirect(self.get_success_url())

        
    def get_success_url(self):
        self.object = self.get_object()
        indirizzo =  str('/view_post/'+str(self.object.id))
        return  indirizzo 

blog/templates/adminbase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <a href="{% url 'adminpostslist' %}">Tutti i post</a> | 
    </div>
    {% block content %}

    {% endblock %}
</body>
</html>

blog/templates/adminlogin.html
{% extends 'base.html' %}

{% block title %}Admin Login{% endblock %}

{% block content %}
<style>
    .errorlist {
        color: red;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Admin Login Form</h3>
            <hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">Login as a Admin</button>
                {% if error %}
                <li style="color: red;">{{error}}</li>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/adminpostslist.html
<!-- view_post.html -->
{% extends 'adminbase.html' %}
{% block title %} Tutti i post {% endblock %}
{% block content %}

<div class = "container"> 
    <div class="row">
        
            <h3>Tutti i post</h3> <hr>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>SN</th>
                        <th>Titolo</th>
                        <th>Immagine</th>
                        <th>Visite al post</th>
                    </tr>

                </thead>
                <tbody>
                        {% for p in allposts%}
                        <tr>
                            <td>{{forloop.counter}}</td>
                            <td>{{p.title}}</td>
                            <td><img src="{{p.image.url}}" style ="height: 60px;" alt=""></td>
                            <td>{{p.view_count}}</td>
                        </tr>
                        {%endfor%}
                    
                </tbody>
            </table>

            <a href="/logout">logout</a>        
    </div>
</div>


{% endblock %}

blog/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}   {% endblock %}</title>
</head>
<body>
    <div id="content">
        {% block content %}   {% endblock %}
    </div>

<a class="dropdown-item" href="{% url 'customerlogout' %}">Logout</a>


</body>
</html>

blog/templates/create_blog_post.html
<!-- In questo template, 
    si può usare l'oggetto form per rendere i campi del form
     e il token csrf e il pulsante di invio -->


<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create Post">
    </form>
    

blog/templates/create_post.html
<!-- create_post.html -->

{% extends 'base.html' %}

{% block title %}Create Post{% endblock %}

{% block content %}

    <h2>Create Post</h2>
    <form method = "post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
    <button type="submit">Create Post</button>
    </form>
{% endblock %}

blog/templates/elimina_post.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

blog/templates/login.html
<!-- login.html -->

{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock %}

blog/templates/register.html
<!-- register.html ciao ciao    -->

{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
    <h2>Register</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
{% endblock %}

blog/templates/view_post.html
<!-- view_post.html -->

{% extends 'base.html' %}

{% block title %} {{ post.title }} {% endblock %}

{% block content %}
<div class="container">

 
    <div class="row">
        <div class="col-md-4">
            <h2>{{ blogpost.title }}</h2>
            <p>{{ blogpost.content }}</p>
            <p>{{ blogpost.traccia }}</p>
            <div class="row">
                
                {% if blogpost.image %}
                <img
                max-width: 10%;
                height: 10%;
                src= "{{ blogpost.image.url }}">
                {% for immagine in blogpost.blogimage_set.all %}
                    <div="col-md-4">
                    <img  max-width: 10%;
                    height: 10%;
                    src= " {{immagine.image.url }}">
                    </div>
                {% endfor %}
                {% endif %}
            </div>
            <a class="dropdown-item" 
            href="{% url 'modifica_post' pk=blogpost.id %}"
            data-toggle="tooltip" data-placement="right" 
            title="Modifica il post">
            <i class="fas fa-edit"></i> 
            Modifica Post
            </a>

            <a class="dropdown-item" 
            href="{% url 'elimina_post' pk=blogpost.id %}" 
            onclick="return confirm('Sei sicuro di voler eliminare il post?')" 
            class="btn btn-circle btn-danger m-l-10 m-r-10" 
            data-toggle="tooltip" data-placement="right" 
            title="Elimina il Post">
            <i class="fas fa-trash"></i>
            Elimina Post
            </a>




        </div>
    </div>
</div>

    <p>Written by {{ post.author }} on {{ post.created_at }}</p>

{% endblock %}